### ISSUE TITLE
NMEA messages possibly trailed by out-of-spec checksum

### ISSUE THREAD

**Issue by cr** [cr/hx870#15]
NMEA messages are trailed by varying appendices like `*7D` in the dump. I am suspecting that they may be HX message protocol checksums, but they could be part of the NMEA standard as well. If it's not standard, they need to be validated and stripped from the output.

This requires some quick NMEA spec digging for verification.

**Comment by johannessen** [comment]
It *is* a checksum, but I’m not sure of its utility here. The USB link is much more stable than early serial links, and in contrast to real-time display or use of navigation information, safety of life is not really an issue in our case. It might be best to ignore the checksum altogether.

Both the [Wikipedia article on NMEA 0183](https://en.wikipedia.org/wiki/NMEA_0183#C_implementation_of_checksum_generation) as well as [that HX851 web page](http://www.paul.sladen.org/toys/vertex/hx851e.html#automatic-control-mode) mention checksum algorithms (the latter in Python, no less). No clue if they match whatever the HX870 implements.

**Comment by cr** [comment]
Interesting. Thanks for checking!

It looks like Yaesu has extended the NMEA message format (beginning with $) and its checksumming to support their proprietary message/command protocol (beginning with #) as well.

I am rather confident that the HX851 and later HX870 and HX890 models use the same message formats and checksumming.

**Comment by cr** [comment]
The checksum is part of the NMEA spec and should be handled transparently by hxtool.
