### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by EdwardFinegan** [cr/hx870#21]
When I run hxtool --help I'm getting the following syntax error. Any thoughts on what may be causing this? I'm Assuming its something in my python environment. This is on OS X Mojave. I have installed the latest python version from the python website. Thanks!

`Traceback (most recent call last):
  File "/usr/local/bin/hxtool", line 9, in <module>
    load_entry_point('hxtool==0.2.1a0', 'console_scripts', 'hxtool')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/hxtool/__init__.py", line 19
    logger.warning(f"Multiple devices detected, using {devices[0].tty}")
                                                                      ^
SyntaxError: invalid syntax`

**Comment by cr** [comment]
Python 2.7 is not supported and hxtool requires Python 3.6 or later. I recommend creating a virtual environment with Python 3.7 which is the current version and what I use for developement.

**Comment by cr** [comment]
> I have installed the latest python version from the python website.

I don't know which Python version you installed, but from the error it looks like your environment is still using Mac OS's system Python 2.7. You shouldn't try to switch the system away from its default Python interpreter, because it will cause nasty errors in other places. That's why setting up a dedicated virtual environment for hxtool is crucial.

**Comment by EdwardFinegan** [comment]
Thanks got it working. Had hxtool installed in the virtual environment and on the system. When I ran it the path came up with the system install. 

Is there a way to dump the gps logger file?

**Comment by cr** [comment]
Great!

> Is there a way to dump the gps logger file?

Not really, at least for now. There are internal functions to dump the raw data and decode the bytes into coordinates, but since there has been no solid proposal for an export format (GPX?), these functions haven't made it into the command line interface, yet.

**Comment by cr** [comment]
@edfinegan, #22 just landed experimental GPX export. Please feel free to give it a try and provide some feedback whether the GPX file works for your software.

**Comment by cr** [comment]
Please provide feedback regarding log export in #6.
