### ISSUE TITLE
Only the first 201 GPS log points are decoded

### ISSUE THREAD

**Issue by johannessen** [cr/hx870#28]
With my HX870E (firmware 2.04), [`decode_gps_log()`](https://github.com/cr/hx870/blob/16ced589937bb87709250309e79ce87faf6a8b3e/hxtool/cli/gpslog.py#L97) fails to decode more than 201 GPS log points, even though the log is much longer than that.

It looks like the raw log data is chunked. Each chunk ends with twelve `ff` bytes (starting at offset `0xff4`), causing the current implementation to break the decode loop and return after only the first chunk has been read.

Each chunk is 4 KiB long. Each chunk starts with 64 header bytes. `01 00 01 0b` doesn’t look like a magic constant to me: The first byte is incremented each time the header is repeated.

These are the first 16 bytes in each of the header sections that my log currently contains:
````
0x0000:  01 00 01 0b 7f 00 00 00 3c 00 00 00 00 00 43 0b
0x1000:  02 00 01 0b 7f 00 00 00 05 00 00 00 00 00 79 0b
0x2000:  03 00 01 0b 7f 00 00 00 05 00 00 00 00 00 78 0b
0x3000:  04 00 01 0b 7f 00 00 00 05 00 00 00 00 00 7f 0b
`````
The bitfield looks identical for the first three chunks, each beginning with 201 zeros. The last bitfield has 176 zeros. This adds up to 779, which is exactly the number of points my log currently contains.

The “unknown” data looks identical for the first three chunks with `00 0c 8c 14` for each. The last chunk has `00 fc 8c 1c`.

**Comment by cr** [comment]
I don't know what's going on there, but I have a refactored MediaTek protocol class in the development pipeline which you might want to run against your test case. I just need to find the time to rebase it onto latest master (and there will be plenty of conflicts around "waypoints/trackpoints" after the last PR).

**Comment by johannessen** [comment]
Sure thing!

**Comment by johannessen** [comment]
The issue is still reproducible with 38bfcd7351912417f1f8d0d16996f4bb2fe59750 (0.3.1a1).

It looks like the issue is fundamentally that `locus.py` classes (specifically, [`Locus`](https://github.com/cr/hx870/blob/a0b4b85f10ddead99344687087b64fa32bf84a90/hxtool/locus.py#L198) and [`LocusLog`](https://github.com/cr/hx870/blob/a0b4b85f10ddead99344687087b64fa32bf84a90/hxtool/locus.py#L170)) don’t handle chunks, so any log chunks after the first one are effectively ignored during decoding.

**Comment by mbof** [comment]
Should this be marked as fixed?

**Comment by cr** [comment]
Yes, indeed! Thanks for checking.
